services:
  - type: web
    name: attendance-system-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        sync: false
      - key: LOG_LEVEL
        value: info
